### ISSUE TITLE
Conflict develop and 024

### ISSUE THREAD

**Issue by Hakamatsu** [Erwan-BR/PLT#49]
When I check the last update the changes in Player.cpp doesnt appear.
You'll see a "new branch" 024 with some changes, those changes should fit the dia changes of the develop section but leads to error in the actual 024 connected to before the merge.

Can you check this ?

**Comment by Erwan-BR** [comment]
The Player and Game code **are not** in the latest version of develop because they were not required for [milestone 3](https://github.com/Erwan-BR/PLT/milestone/3).

The code was removed because it would have been necessary to do the UTs and they weren't done.

When all Player and Game methods have been implemented, a PR will be made to add Player and Game content to develop.

@Hakamatsu

**Comment by Erwan-BR** [comment]
However, I don't see a new 024 branch on the project.

I've just had a look at it and I think it's because you've modified the cpp, which shouldn't have been done because the version of dia doesn't match.

In this branch, you shouldn't touch DevelopmentCard, which has been merged correctly into develop.

@Hakamatsu
